### PR TITLE
Move atoms components into the atoms folder

### PR DESCRIPTION
**Pull request by lewisnyman**
When I got to a point where I wanted to modify the base content it took me a while to figure out where they were coming from and the best way to modify/overwrite the content. Do I fork the style-prototype repo and update the bower reference or is there an simpler way?

I ended up realising that I could just copy the folders over to the atoms directory, which is kind of obvious once you realise that's the magic, there's no reason to learn this if you use the sub-generator to create patterns.

It seems like an improvement for newbies and a good demonstration of functionality that is otherwise abstracted away.

What do you think?

### CODE REVIEW

**Comment by Snugug** [comment]
I'm very specifically not going to do this, but what is needed I feel is better documentation around the plugin system.

The idea of the plugin system is you can use patterns from an external library without needing to maintain upstream changes. Think Twitter Bootstrap or Zurb Foundation. Then, if you want to change an individual pattern, simply place a pattern with the same name in the same spot in your project. This allows for upstream updates while preserving overrides.

The added advantage to the plugin system is that each style prototype then becomes itself a plugin that can be used for other projects so, say you're building a number of sites using the same base styling; you can create your base and each individual one w/o having them all go out of sync.

**Comment by Snugug** [comment]
Something I meant to do after Austin that I never got around to doing was including a `--demo` flag allowing for example files to be included.

**Comment by lewisnyman** [comment]
Sure, that make sense. You truly are the king of abstraction :smile_cat: It has taken a fair amount of time to generate all the components so making them transferable would be good. I've also had to spend time rewriting some of the content to be more industry appropriate, so it doesn't stray too far from the required tone.

**Comment by Snugug** [comment]
Well if it's shareable, package it up as something Bower can pull down and boom! You've got yourself a plugin that you can reuse.

**Pull request closed without merging**
